blank_issues_enabled: false
contact_links:
  - name: ü§ù –ü–∏—Ç–∞–Ω–Ω—è –∞–±–æ –¥–æ–ø–æ–º–æ–≥–∞ –ø–æ–∑–∞ —à–∞–±–ª–æ–Ω–∞–º–∏
    url: https://t.me/sol_di
    about: –Ø–∫—â–æ –≤–∞—à–µ –ø–∏—Ç–∞–Ω–Ω—è –Ω–µ —Å—Ç–æ—Å—É—î—Ç—å—Å—è –±–∞–≥—ñ–≤ —á–∏ —Ñ—ñ—á ‚Äî –ø–∏—à—ñ—Ç—å —Å—é–¥–∏
